### ISSUE TITLE
VdW - Kickoff 

### ISSUE THREAD

**Issue by Majed610** [Aliado-Leipzig/VNG#9]
- [x] Create staging account and install WordPress
- [x] Prepare theme and template
(here you can use the VNG-Stiftung theme to built on, so you don't have to start from scratch. 

- Lin for the XD https://xd.adobe.com/view/c6b94bbf-7f4c-46fd-b540-c692549c45fd-93ea/

Elements of the Template: 

 **Navi & Menus:** 

- [x]  Main Navigation - Sticky Header 
(Just like the Balance The header decreases its size on scroll) 

- [x] Sub-Navi bottom of Page - Sticky Subnavi 
(This navigation remains at all times on the bottom of the page) 

- [x] Footer as in XD 

- [x] responsive Navi 
Hamburger menu sticky 
Lower Menü as drop-up List 

**Pages:**
These pages should be build 
- Homepage 
- Aktuelles (News) 
- Page for Themenbereiche (Kategories) 
- Projekte (page for projects xd 6/14) 
- Search and result page 
- Kontakt (contact form) 

**Header & Hero:**
Heros should be full screen at 100vh height or at least have the option to change to 100vh. 

*I will add all necessary SVGs in the task here later today

**Comment by Majed610** [comment]
Assets for the Website:

Fonts:
[ITC Officina-FS-WebFonts-40642423.zip](https://github.com/Aliado-Leipzig/VNG/files/8304113/ITC.Officina-FS-WebFonts-40642423.zip)

Pictures:
![motivbild](https://user-images.githubusercontent.com/89200332/158996884-59d1a7f4-3a8e-48b5-8104-ff16818367bb.svg)
![logo 4c zw ohne VNG Stiftung](https://user-images.githubusercontent.com/89200332/158996888-0b65dcd5-eded-4242-9d04-52a22d3561a1.svg)
![logo 4c zw](https://user-images.githubusercontent.com/89200332/158996890-e28f0e20-5a05-4c4a-90bf-ca0881d542fd.svg)
![VdW-Icon_Kultur Geschichte](https://user-images.githubusercontent.com/89200332/158996958-72ac1217-1983-4c85-b0dc-2a6f75735dc8.png)
![VdW-Icon_Natur Klima](https://user-images.githubusercontent.com/89200332/158996960-fb1f8302-17ba-45d7-a6bd-384087cd19ea.png)
![VdW-Icon_Teilhabe Integration](https://user-images.githubusercontent.com/89200332/158996963-ca4b2b35-97ec-4b32-8ab7-cba042c924c8.png)

Icons:
![VdW-Icon_Wissen Lernen](https://user-images.githubusercontent.com/89200332/158996956-e9b86259-be79-4344-ae7f-3c56a26eff3b.png)
![VdW-Icon_Gesundheit Sport](https://user-images.githubusercontent.com/89200332/158996957-afda75e7-dd95-4e86-859b-86fbddf3d7c6.png)

**Comment by Mirsho** [comment]
Hi Majed!

Development is going well. The desktop header and footer are nearly ready. Needs little fitting and adapting to mobile but the main build is done.

Mobile
- [ ] Header: Hamburguer menu
- [ ] Footer: Responsive Navi
Hamburger menu sticky
Lower Menü as drop-up List

Pages:
These pages should be build

Homepage
- [ ] Aktuelles (News)
- [ ] Page for Themenbereiche (Kategories)
- [ ] Projekte (page for projects xd 6/14)
- [ ] Search and result page
- [ ] Kontakt (contact form)
- [ ] Header & Hero:
Heros should be full screen at 100vh height or at least have the option to change to 100vh.

I  have a **question about this last point**. If the heros are this part of the pages:

![image](https://user-images.githubusercontent.com/50135963/159728003-72b737b4-58af-4fa6-a627-b53da7921b2c.png)

![image](https://user-images.githubusercontent.com/50135963/159728280-793a59c5-7ceb-4c63-80db-2877a2938f8f.png)

Do you want them to look (at first moment) 100vh, like how is shown in this draft?
https://xd.adobe.com/view/c6b94bbf-7f4c-46fd-b540-c692549c45fd-93ea/screen/4b71323e-f95e-4bc0-af5d-b0b0863bde86/specs/

Or how's the idea?

Apart from that, I need some icons such as Facebook, phone, mail, etc. I cant take them from the XD. Can you please send me the draft with assets download enabled?

As soon as the header+footer+navigation is ready, I'll build and style single pages.

You can check the current status at: https://vdw.vng.aliado.rocks/

And finally, I want to mention that:

The footer navigation buttons are styled as you mentioned, removing side white lines for the current menu button:

![image](https://user-images.githubusercontent.com/50135963/159730711-6f310010-82d1-4305-ba60-74111f504cac.png)

I kept the Stiftung "go to top" button because I think it looked good:

![image](https://user-images.githubusercontent.com/50135963/159730015-8a8b72af-9149-4877-a735-a4dd8e7f0014.png)

Write me if you have any comment. Thanks!

**Comment by Majed610** [comment]
Hi Adrian, 

it looks really well. 

Some Comments: 
- Can we increase the size of the logo to fit the white header space? 
- Please set the hero height at 100 vh
- The go to top button is fine
- I will upload the icons here as soon as i have them 

Thanks
